spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

  kafka:
    bootstrap-servers: "192.168.1.16:9092,192.168.1.242:9092"
    producer:
      retries: 0
      batch-size: 4096
      buffer-memory: 40960
      acks: "1"

com:
  saucesubfresh:
    rpc:
      server:
        server-address: 127.0.0.1
        server-port: 5200
        server-name: open-cache-app
    cache:
      namespace: open-cache-app # 当多个应用使用同一个 redis 时为了区分相同 cacheName
      instance-id: 127.0.0.1:8080 # 可以为服务器 ip：应用端口



